apiVersion: v1
kind: Service
metadata:
  name: spire-server-headless
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: spire-server
  ports:
  - name: grpc
    port: 8081
    targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spire-server
  ports:
  - name: grpc
    port: 8081
    targetPort: grpc
  - name: health
    port: 8080
    targetPort: health
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server-bootstrap
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: spire-server
  ports:
  - name: grpc
    port: 8081
    targetPort: grpc
