apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
  labels:
    app.kubernetes.io/part-of: ardur
    app.kubernetes.io/component: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
