// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package kernelcapture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProcessExec returns the embedded CollectionSpec for processExec.
func loadProcessExec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessExecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processExec: %w", err)
	}

	return spec, err
}

// loadProcessExecObjects loads processExec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processExecObjects
//	*processExecPrograms
//	*processExecMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessExecObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessExec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processExecSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecSpecs struct {
	processExecProgramSpecs
	processExecMapSpecs
}

// processExecSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
}

// processExecMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// processExecObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecObjects struct {
	processExecPrograms
	processExecMaps
}

func (o *processExecObjects) Close() error {
	return _ProcessExecClose(
		&o.processExecPrograms,
		&o.processExecMaps,
	)
}

// processExecMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *processExecMaps) Close() error {
	return _ProcessExecClose(
		m.Events,
	)
}

// processExecPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecPrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
}

func (p *processExecPrograms) Close() error {
	return _ProcessExecClose(
		p.HandleSchedProcessExec,
	)
}

func _ProcessExecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processexec_bpfel.o
var _ProcessExecBytes []byte
