//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AgentPassport) DeepCopyInto(out *AgentPassport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AgentPassport) DeepCopy() *AgentPassport {
	if in == nil {
		return nil
	}
	out := new(AgentPassport)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentPassport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentPassportList) DeepCopyInto(out *AgentPassportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPassport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentPassportList) DeepCopy() *AgentPassportList {
	if in == nil {
		return nil
	}
	out := new(AgentPassportList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentPassportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentPassportSpec) DeepCopyInto(out *AgentPassportSpec) {
	*out = *in
	out.Identity = in.Identity
	if in.Provenance != nil {
		in, out := &in.Provenance, &out.Provenance
		*out = new(ProvenanceSpec)
		**out = **in
	}
	in.Intent.DeepCopyInto(&out.Intent)
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(BaselineSpec)
		**out = **in
	}
	in.Trust.DeepCopyInto(&out.Trust)
	in.Credential.DeepCopyInto(&out.Credential)
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(GovernanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *AgentPassportSpec) DeepCopy() *AgentPassportSpec {
	if in == nil {
		return nil
	}
	out := new(AgentPassportSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IntentSpec) DeepCopyInto(out *IntentSpec) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
	if in.PermittedActions != nil {
		in, out := &in.PermittedActions, &out.PermittedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *IntentSpec) DeepCopy() *IntentSpec {
	if in == nil {
		return nil
	}
	out := new(IntentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TrustSpec) DeepCopyInto(out *TrustSpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(TrustThresholds)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TrustSpec) DeepCopy() *TrustSpec {
	if in == nil {
		return nil
	}
	out := new(TrustSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TrustThresholds) DeepCopyInto(out *TrustThresholds) {
	*out = *in
	if in.FullTier != nil {
		in, out := &in.FullTier, &out.FullTier
		*out = new(float64)
		**out = **in
	}
	if in.LimitedTier != nil {
		in, out := &in.LimitedTier, &out.LimitedTier
		*out = new(float64)
		**out = **in
	}
}

func (in *TrustThresholds) DeepCopy() *TrustThresholds {
	if in == nil {
		return nil
	}
	out := new(TrustThresholds)
	in.DeepCopyInto(out)
	return out
}

func (in *CredentialSpec) DeepCopyInto(out *CredentialSpec) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SelectiveDisclosure != nil {
		in, out := &in.SelectiveDisclosure, &out.SelectiveDisclosure
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *CredentialSpec) DeepCopy() *CredentialSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentPassportStatus) DeepCopyInto(out *AgentPassportStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.LogIndex != nil {
		in, out := &in.LogIndex, &out.LogIndex
		*out = new(int64)
		**out = **in
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(GovernanceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentPassportStatus) DeepCopy() *AgentPassportStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPassportStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GovernanceSpec) DeepCopyInto(out *GovernanceSpec) {
	*out = *in
	if in.DeclarationRef != nil {
		in, out := &in.DeclarationRef, &out.DeclarationRef
		*out = new(DeclarationReference)
		**out = **in
	}
	if in.InlineDeclaration != nil {
		in, out := &in.InlineDeclaration, &out.InlineDeclaration
		*out = new(InlineDeclaration)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionTTL != nil {
		in, out := &in.SessionTTL, &out.SessionTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.EnforcementPolicy != nil {
		in, out := &in.EnforcementPolicy, &out.EnforcementPolicy
		*out = new(EnforcementPolicy)
		(*in).DeepCopyInto(*out)
	}
}

func (in *GovernanceSpec) DeepCopy() *GovernanceSpec {
	if in == nil {
		return nil
	}
	out := new(GovernanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GovernanceStatus) DeepCopyInto(out *GovernanceStatus) {
	*out = *in
	if in.LastDecisionTime != nil {
		in, out := &in.LastDecisionTime, &out.LastDecisionTime
		*out = (*in).DeepCopy()
	}
}

func (in *GovernanceStatus) DeepCopy() *GovernanceStatus {
	if in == nil {
		return nil
	}
	out := new(GovernanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DeclarationReference) DeepCopyInto(out *DeclarationReference) {
	*out = *in
}

func (in *DeclarationReference) DeepCopy() *DeclarationReference {
	if in == nil {
		return nil
	}
	out := new(DeclarationReference)
	in.DeepCopyInto(out)
	return out
}

func (in *InlineDeclaration) DeepCopyInto(out *InlineDeclaration) {
	*out = *in
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedResources != nil {
		in, out := &in.AllowedResources, &out.AllowedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedResourceFamilies != nil {
		in, out := &in.AllowedResourceFamilies, &out.AllowedResourceFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSideEffects != nil {
		in, out := &in.AllowedSideEffects, &out.AllowedSideEffects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *InlineDeclaration) DeepCopy() *InlineDeclaration {
	if in == nil {
		return nil
	}
	out := new(InlineDeclaration)
	in.DeepCopyInto(out)
	return out
}

func (in *EnforcementPolicy) DeepCopyInto(out *EnforcementPolicy) {
	*out = *in
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *EnforcementPolicy) DeepCopy() *EnforcementPolicy {
	if in == nil {
		return nil
	}
	out := new(EnforcementPolicy)
	in.DeepCopyInto(out)
	return out
}
