FROM registry.fedoraproject.org/fedora:43

RUN dnf -y install --setopt=install_weak_deps=False \
    golang \
    clang \
    llvm \
    llvm-devel \
    bpftool \
    libbpf-devel \
    kernel-headers \
    make \
    git \
    findutils \
    which \
    procps-ng \
    iproute \
    && dnf clean all

WORKDIR /workspace
