apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spire-server-configmap-role
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spire-server-configmap-role-binding
  namespace: spire-system
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spire-server-configmap-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-server-trust-role
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-server-trust-role-binding
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: ardur
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-server-trust-role
